export { default as bag } from './bag.svg';
export { default as globe } from './globe.svg';
export { default as arrowUp } from './icons/arrow-up.svg';
export { default as shapeCursor } from './shape-cursor.svg';
export { default as shopifyBag } from './shopify-bag.svg';
export { default as tagBg } from './tag-bg.svg';
export { default as tag } from './tags.svg';
export { default as uiUxBg } from './ui-ux-tiles-bg.svg';
export { default as webDevBg } from './webDevBg.svg';
