export { default as ehsan } from './ehsan_vice-president.jpg';
export { default as adi } from './marzuk_founder.jpeg';
export { default as person1 } from './person_1.jpg';
export { default as person2 } from './person_2.jpg';
export { default as person3 } from './person_3.jpg';
export { default as person4 } from './person_4.webp';
export { default as person5 } from './person_5.webp';
export { default as person6 } from './person_6.webp';
export { default as zunayed } from './zunayed_co-founder.jpg';
